In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Machine Learning Models
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor

# Data Preparation
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Evaluation Metrics
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

# Display all columns
pd.set_option("display.max_columns", None)

In [6]:
df = pd.read_csv("oil_sales_assignment_data.csv")
print("Dataset loaded successfully!")
df.head()

Dataset loaded successfully!

,city,store_name,manufacturer,brand,class,size,sku,price_bracket,year,month,value_sales,volume_sales,average_price
0,AL BAHA,HM No 57296 GS-CENTER-AL BAHA MAIN RD AL BAHA,NOVA FOODS,LARA,COCONUT,0.75L,LARA COCONUT 0.75L TWIN PACK,21-30,2024,12,830.86,30.1,27.6
1,AL KHARJ,HM No 55697 GS-CENTER-AL KHARJ MAIN RD AL K...,PALM & GRAIN GROUP,NAJMA,CANOLA,0.5L,NAJMA CANOLA 0.5L TWIN PACK,41-50,2024,10,373.10,9.1,41.0
2,RIYADH,HM No 86781 GS-CENTER-RIYADH MAIN RD RIYADH,AL HILAL INDUSTRIES,BAYTNA,SUNFLOWER,0.75L,BAYTNA SUNFLOWER 0.75L ECO,101+,2023,1,171.70,1.7,101.0
3,DAMMAM,HM No 95753 GS-CENTER-DAMMAM MAIN RD DAMMAM,PALM & GRAIN GROUP,NOUR,CORN,0.6L,NOUR CORN 0.6L TWIN PACK,61-70,2022,2,1226.10,20.1,61.0
4,JAZAN,HM No 56338 GS-CENTER-JAZAN MAIN RD JAZAN,DESERT SUN CO,NOUR,VEGETABLE,1L,NOUR VEGETABLE 1L,81-90,2024,2,996.30,12.3,81.0

In [7]:
#Data Exploration
print("Dataset Shape:", df.shape)


print("\nDataset Information:")
df.info()


print("\nMissing Values:")
print(df.isnull().sum())


print("\nDescriptive Statistics:")
display(df.describe())

Dataset Shape: (2000, 13)

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   city           2000 non-null   str
 1   store_name     2000 non-null   str
 2   manufacturer   2000 non-null   str
 3   brand          2000 non-null   str
 4   class          2000 non-null   str
 5   size           2000 non-null   str
 6   sku            2000 non-null   str
 7   price_bracket  2000 non-null   str
 8   year           2000 non-null   int64
 9   month          2000 non-null   int64
 10  value_sales    2000 non-null   float64
 11  volume_sales   2000 non-null   float64
 12  average_price  2000 non-null   float64
dtypes: float64(3), int64(2), str(8)
memory usage: 203.3 KB

Missing Values:
city             0
store_name       0
manufacturer     0
brand            0
class            0
size             0
sku              0
price_bracket    0
year             0
month            0
value_sales      0
volume_sales     0
average_price    0
dtype: int64

Descriptive Statistics:

              year        month  value_sales  volume_sales  average_price
count  2000.000000  2000.000000  2000.000000   2000.000000    2000.000000
mean   2022.990500     6.639500   614.839355      9.972100      60.990230
std       0.820211     3.468942   750.794991      9.862369      29.457029
min    2022.000000     1.000000     6.960000      0.500000      11.000000
25%    2022.000000     4.000000   132.000000      2.900000      37.337500
50%    2023.000000     7.000000   368.320000      7.000000      61.000000
75%    2024.000000    10.000000   794.100000     13.800000      81.000000
max    2024.000000    12.000000  6253.200000     81.700000     140.000000

In [15]:
# #Encode Categorical Variables
# le = LabelEncoder()
# categorical_columns = [
#     'city',
#     'store_name',
#     'manufacturer',
#     'brand',
#     'class',
#     'size',
#     'sku',
#     'price_bracket'
# ]

# for column in categorical_columns:
#     df[column] = le.fit_transform(df[column])

# print("Categorical variables encoded successfully!")
# df.head()

In [16]:
#  Prepare Features and Target
X = df.drop(columns=['value_sales'])
y = df['value_sales']

print("Feature Matrix Shape:", X.shape)
print("Target Shape:", y.shape)

Feature Matrix Shape: (2000, 12)
Target Shape: (2000,)

In [17]:
#Split the Dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training Set:", X_train.shape)
print("Testing Set:", X_test.shape)

Training Set: (1600, 12)
Testing Set: (400, 12)

In [19]:
# #Feature Scaling
# scaler = StandardScaler()

# # fit on training data and transform it
# X_train_scaled = scaler.fit_transform(X_train)

# # transform test data using the same scaler
# X_test_scaled = scaler.transform(X_test)

# print("Feature scaling completed.")

In [ ]:
# # model 1 linear Regression
# linear_model = LinearRegression()
# linear_model.fit(X_train_scaled, y_train)
# print("Intercept:")
# print(linear_model.intercept_)

# coefficients = pd.DataFrame({
#     "Feature": X.columns,
#     "Coefficient": linear_model.coef_
# })

# coefficients


# coefficients["Absolute Coefficient"] = coefficients["Coefficient"].abs()

# coefficients = coefficients.sort_values(
#     by="Absolute Coefficient",
#     ascending=False
# )

# coefficients


# # Predictions
# y_pred_train = linear_model.predict(X_train_scaled)

# y_pred_test = linear_model.predict(X_test_scaled)

# # Training RMSE
# train_rmse = np.sqrt(
#     mean_squared_error(y_train, y_pred_train)
# )

# # Test RMSE
# test_rmse = np.sqrt(
#     mean_squared_error(y_test, y_pred_test)
# )

# # Training R²
# train_r2 = r2_score(y_train, y_pred_train)

# # Test R²
# test_r2 = r2_score(y_test, y_pred_test)

# print("Linear Regression Performance")

# print(f"Training RMSE : {train_rmse:.2f}")
# print(f"Testing RMSE  : {test_rmse:.2f}")

# print(f"Training R²   : {train_r2:.4f}")
# print(f"Testing R²    : {test_r2:.4f}")

Intercept:
617.12899375
Linear Regression Performance
Training RMSE : 283.45
Testing RMSE  : 296.35
Training R²   : 0.8597
Testing R²    : 0.8334

In [9]:

# label Encoding + no Scaling + linear Regression 1
# 1 Label Encoding
categorical_columns = [
    "city",
    "store_name",
    "manufacturer",
    "brand",
    "class",
    "size",
    "sku",
    "price_bracket"
]

le = LabelEncoder()
for column in categorical_columns:
    df[column] = le.fit_transform(df[column])


#2 features and Target
X = df.drop(columns=["value_sales"])
y = df["value_sales"]


#3split Dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42
)

print("Training Shape :", X_train.shape)
print("Testing Shape  :", X_test.shape)


#4 Train linear regression
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)


#5model equation
print("Linear Regression Equation")
print(f"Intercept : {linear_model.intercept_:.4f}")

coef_df = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": linear_model.coef_
})

coef_df["Absolute Coefficient"] = coef_df["Coefficient"].abs()
coef_df = coef_df.sort_values(
    by="Absolute Coefficient",
    ascending=False
)

print("\nFeature Coefficients")
print(coef_df)


#6 predictions
y_pred_train = linear_model.predict(X_train)
y_pred_test = linear_model.predict(X_test)


# 7Evaluation

train_rmse = np.sqrt(
    mean_squared_error(y_train, y_pred_train)
)

test_rmse = np.sqrt(
    mean_squared_error(y_test, y_pred_test)
)

train_r2 = r2_score(
    y_train,
    y_pred_train
)

test_r2 = r2_score(
    y_test,
    y_pred_test
)


# 8results
print("Experiment 1 Results")
print(f"Training RMSE : {train_rmse:.2f}")
print(f"Testing RMSE  : {test_rmse:.2f}")
print(f"Training R²   : {train_r2:.4f}")
print(f"Testing R²    : {test_r2:.4f}")

#9 save
results = pd.DataFrame({
    "Model": ["Linear Regression"],
    "Encoding": ["Label Encoding"],
    "Scaling": ["None"],
    "Train RMSE": [train_rmse],
    "Test RMSE": [test_rmse],
    "Train R2": [train_r2],
    "Test R2": [test_r2]
})

print("\nComparison Table")
print(results)

Training Shape : (1600, 12)
Testing Shape  : (400, 12)
Linear Regression Equation
Intercept : -1929.7602

Feature Coefficients
          Feature  Coefficient  Absolute Coefficient
3           brand    95.209842             95.209842
10   volume_sales    64.011011             64.011011
4           class    14.470626             14.470626
11  average_price     9.855683              9.855683
7   price_bracket    -3.204368              3.204368
0            city     3.031874              3.031874
9           month    -2.410551              2.410551
2    manufacturer     1.148195              1.148195
5            size     0.867378              0.867378
8            year     0.658280              0.658280
6             sku    -0.594269              0.594269
1      store_name    -0.002796              0.002796
Experiment 1 Results
Training RMSE : 283.45
Testing RMSE  : 296.35
Training R²   : 0.8597
Testing R²    : 0.8334

Comparison Table
               Model        Encoding Scaling  Train RMSE   Test RMSE  \
0  Linear Regression  Label Encoding    None  283.452755  296.346821

   Train R2   Test R2
0  0.859651  0.833378

In [11]:

# label Encoding + StandardScaler + Linear Regression 2

categorical_columns = [
    "city",
    "store_name",
    "manufacturer",
    "brand",
    "class",
    "size",
    "sku",
    "price_bracket"
]

le = LabelEncoder()
for column in categorical_columns:
    df[column] = le.fit_transform(df[column])




X = df.drop(columns=["value_sales"])
y = df["value_sales"]


X_train, X_test, y_train, y_test = train_test_split(
    X,  y,
    test_size=0.20,
    random_state=42
)

# standard Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


#train Model
linear_model = LinearRegression()
linear_model.fit(X_train_scaled, y_train)


#coefficients
coef_df = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": linear_model.coef_
})

coef_df["Absolute Coefficient"] = coef_df["Coefficient"].abs()
coef_df = coef_df.sort_values(
    by="Absolute Coefficient",
    ascending=False
)

print(coef_df)


#prediction
y_pred_train = linear_model.predict(X_train_scaled)
y_pred_test = linear_model.predict(X_test_scaled)

#evaluation
train_rmse = np.sqrt(
    mean_squared_error(y_train, y_pred_train)
)

test_rmse = np.sqrt(
    mean_squared_error(y_test, y_pred_test)
)

train_r2 = r2_score(
    y_train,
    y_pred_train
)

test_r2 = r2_score(
    y_test,
    y_pred_test
)

#result
print("Experiment 2")
print("Label Encoding + StandardScaler + Linear Regression")
print(f"Training RMSE : {train_rmse:.2f}")
print(f"Testing RMSE  : {test_rmse:.2f}")
print(f"Training R²   : {train_r2:.4f}")
print(f"Testing R²    : {test_r2:.4f}")


#save
results = pd.DataFrame({
    "Model":["Linear Regression"],
    "Encoding":["Label Encoding"],
    "Scaling":["StandardScaler"],
    "Train RMSE":[train_rmse],
    "Test RMSE":[test_rmse],
    "Train R2":[train_r2],
    "Test R2":[test_r2]
})

print(results)

          Feature  Coefficient  Absolute Coefficient
10   volume_sales   626.532796            626.532796
11  average_price   295.587059            295.587059
3           brand   273.199966            273.199966
6             sku  -272.414648            272.414648
4           class    20.091984             20.091984
0            city    10.409495             10.409495
7   price_bracket    -9.270693              9.270693
9           month    -8.408821              8.408821
5            size     3.156906              3.156906
2    manufacturer     2.659111              2.659111
1      store_name    -1.607040              1.607040
8            year     0.539560              0.539560
Experiment 2
Label Encoding + StandardScaler + Linear Regression
Training RMSE : 283.45
Testing RMSE  : 296.35
Training R²   : 0.8597
Testing R²    : 0.8334
               Model        Encoding         Scaling  Train RMSE   Test RMSE  \
0  Linear Regression  Label Encoding  StandardScaler  283.452755  296.346821

   Train R2   Test R2
0  0.859651  0.833378