In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import (
mean_squared_error,
mean_absolute_error,
r2_score
)

from scipy import stats

In [28]:
#Part 1: Data Exploration
# Task 1 load the dataset
df = pd.read_csv("oil_sales_assignment_data.csv")
print("Dataset loaded successfully!")

df.head()

Dataset loaded successfully!

,city,store_name,manufacturer,brand,class,size,sku,price_bracket,year,month,value_sales,volume_sales,average_price
0,AL BAHA,HM No 57296 GS-CENTER-AL BAHA MAIN RD AL BAHA,NOVA FOODS,LARA,COCONUT,0.75L,LARA COCONUT 0.75L TWIN PACK,21-30,2024,12,830.86,30.1,27.6
1,AL KHARJ,HM No 55697 GS-CENTER-AL KHARJ MAIN RD AL K...,PALM & GRAIN GROUP,NAJMA,CANOLA,0.5L,NAJMA CANOLA 0.5L TWIN PACK,41-50,2024,10,373.10,9.1,41.0
2,RIYADH,HM No 86781 GS-CENTER-RIYADH MAIN RD RIYADH,AL HILAL INDUSTRIES,BAYTNA,SUNFLOWER,0.75L,BAYTNA SUNFLOWER 0.75L ECO,101+,2023,1,171.70,1.7,101.0
3,DAMMAM,HM No 95753 GS-CENTER-DAMMAM MAIN RD DAMMAM,PALM & GRAIN GROUP,NOUR,CORN,0.6L,NOUR CORN 0.6L TWIN PACK,61-70,2022,2,1226.10,20.1,61.0
4,JAZAN,HM No 56338 GS-CENTER-JAZAN MAIN RD JAZAN,DESERT SUN CO,NOUR,VEGETABLE,1L,NOUR VEGETABLE 1L,81-90,2024,2,996.30,12.3,81.0

In [ ]:

df.tail()

,city,store_name,manufacturer,brand,class,size,sku,price_bracket,year,month,value_sales,volume_sales,average_price
1995,TABUK,HM No 99317 GS-CENTER-TABUK MAIN RD TABUK,NAJDI CONSUMER,LARA,COCONUT,0.5L,LARA COCONUT 0.5L PREMIUM,31-40,2024,11,74.4,2.4,31.0
1996,AL AHSA,HM No 85390 GS-CENTER-AL AHSA MAIN RD AL AHSA,BLUE OASIS CO,LARA,SUNFLOWER,3L,LARA SUNFLOWER 3L,31-40,2022,5,20.0,0.5,40.0
1997,AL KHARJ,HM No 90740 GS-CENTER-AL KHARJ MAIN RD AL K...,NOVA FOODS,NOUR,SUNFLOWER,2.9L,NOUR SUNFLOWER 2.9L,91-100,2023,8,527.8,5.8,91.0
1998,RIYADH,HM No 52893 GS-CENTER-RIYADH MAIN RD RIYADH,NOVA FOODS,NAJMA,CORN,0.75L,NAJMA CORN 0.75L ECO,61-70,2024,6,305.0,5.0,61.0
1999,JEDDAH,HM No 73689 GS-CENTER-JEDDAH MAIN RD JEDDAH,NAJDI CONSUMER,BAYTNA,COCONUT,1.8L,BAYTNA COCONUT 1.8L ECO,101+,2022,4,181.8,1.8,101.0

In [33]:
#task 2 
print("1 number of Rows:", df.shape[0])
print("2 number of Columns:", df.shape[1])

numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns

print("3 numerical Columns:")
print(list(numerical_columns))

categorical_columns = df.select_dtypes(include=['object']).columns
print("4categorical Columns:")
print(list(categorical_columns))

1 number of Rows: 2000
2 number of Columns: 13
3 numerical Columns:
['year', 'month', 'value_sales', 'volume_sales', 'average_price']
4categorical Columns:
['city', 'store_name', 'manufacturer', 'brand', 'class', 'size', 'sku', 'price_bracket']

C:\Users\hp\AppData\Local\Temp\ipykernel_14780\3580975919.py:10: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=['object']).columns

In [38]:
# task 3 check for missing values
print("missing values:", df.isnull().sum())
print("total missing :", df.isnull().sum().sum())

missing values: city             0
store_name       0
manufacturer     0
brand            0
class            0
size             0
sku              0
price_bracket    0
year             0
month            0
value_sales      0
volume_sales     0
average_price    0
dtype: int64
total missing : 0

In [40]:
# task4 generate descriptive statistics
df.describe(include='all')

,city,store_name,manufacturer,brand,class,size,sku,price_bracket,year,month,value_sales,volume_sales,average_price
count,2000,2000,2000,2000,2000,2000,2000,2000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
unique,12,1997,8,10,5,13,1571,10,NaN,NaN,NaN,NaN,NaN
top,AL BAHA,HM No 59035 GS-CENTER-AL AHSA MAIN RD AL AHSA,AL HILAL INDUSTRIES,HILAL,SUNFLOWER,1L,GULF GOLD COCONUT 3L TWIN PACK,21-30,NaN,NaN,NaN,NaN,NaN
freq,199,2,272,223,424,178,5,222,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022.990500,6.639500,614.839355,9.972100,60.990230
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.820211,3.468942,750.794991,9.862369,29.457029
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022.000000,1.000000,6.960000,0.500000,11.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022.000000,4.000000,132.000000,2.900000,37.337500
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.000000,7.000000,368.320000,7.000000,61.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.000000,10.000000,794.100000,13.800000,81.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.000000,12.000000,6253.200000,81.700000,140.000000

In [44]:
#part2 data Preparation, Label Encoding Categorical Variables

le = LabelEncoder()
categorical_cols = [
    'city',
    'store_name',
    'manufacturer',
    'brand',
    'class',
    'size',
    'sku',
    'price_bracket'
]

for col in categorical_cols:
    df[col + '_encoded'] = le.fit_transform(df[col])

print("Encoding completed successfully!")
df.head()

Encoding completed successfully!

,city,store_name,manufacturer,brand,class,size,sku,price_bracket,year,month,value_sales,volume_sales,average_price,city_encoded,store_name_encoded,manufacturer_encoded,brand_encoded,class_encoded,size_encoded,sku_encoded,price_bracket_encoded
0,AL BAHA,HM No 57296 GS-CENTER-AL BAHA MAIN RD AL BAHA,NOVA FOODS,LARA,COCONUT,0.75L,LARA COCONUT 0.75L TWIN PACK,21-30,2024,12,830.86,30.1,27.6,1,302,5,3,1,3,537,2
1,AL KHARJ,HM No 55697 GS-CENTER-AL KHARJ MAIN RD AL K...,PALM & GRAIN GROUP,NAJMA,CANOLA,0.5L,NAJMA CANOLA 0.5L TWIN PACK,41-50,2024,10,373.10,9.1,41.0,2,237,6,4,0,1,648,4
2,RIYADH,HM No 86781 GS-CENTER-RIYADH MAIN RD RIYADH,AL HILAL INDUSTRIES,BAYTNA,SUNFLOWER,0.75L,BAYTNA SUNFLOWER 0.75L ECO,101+,2023,1,171.70,1.7,101.0,8,1487,0,0,3,3,93,0
3,DAMMAM,HM No 95753 GS-CENTER-DAMMAM MAIN RD DAMMAM,PALM & GRAIN GROUP,NOUR,CORN,0.6L,NOUR CORN 0.6L TWIN PACK,61-70,2022,2,1226.10,20.1,61.0,3,1832,6,5,2,2,864,6
4,JAZAN,HM No 56338 GS-CENTER-JAZAN MAIN RD JAZAN,DESERT SUN CO,NOUR,VEGETABLE,1L,NOUR VEGETABLE 1L,81-90,2024,2,996.30,12.3,81.0,5,258,3,5,4,7,944,8

In [ ]:
# part3 Univariate Linear Regression